routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {  D:\laragon\www\greatinfo.loc\resources\views\frontend\front_page
//     return view('welcome');
// });


// Route::get('/', function () {
//     return view('frontend.front_page.index');
// });

Route::get('/', 'Frontend\HomeController@index')->name('home');


// Admin
Route::group(['prefix'=>'admin','middleware'=>'auth'],function(){
	
	//Analytics
	Route::get('/', 'Backend\AnalyticsController@index')->name('analytics');

	//Slides
	Route::resource('slides','Backend\SlidesController');

	//Services
	Route::resource('services','Backend\ServicesController');


});	





Auth::routes();

Route::get('/home', 'HomeController@index')->name('home1');

app/Slide.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Slide extends Model
{
    //
}

app/Http/Controllers/Backend/AnalyticsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Backend\BackendController;

class AnalyticsController extends BackendController
{
    // D:\laragon\www\greatinfo.loc\resources\views\backend\analytics

/*
		protected $data;
	    protected $heading;
	    protected $subheading;
	    protected $vars = [];

 		 $this->heading = 'Information Panel';
   		 $this->subheading = 'Information the Site';

   		 $this->vars = array_add($this->vars,'heading',$this->heading);  
   		 $this->vars = array_add($this->vars,'subheading',$this->subheading);  

    	 return view('backend.dashboard.index')->with($this->vars );

*/


    public function index(){

    	return view('backend.analytics.index');
    } 
}

app/Http/Controllers/Backend/BackendController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BackendController extends Controller
{
    //
}

app/Http/Controllers/Backend/PortfolioItemController.php
<?php

namespace App\Http\Controllers\Backend;

use App\PortfolioItem;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Backend\BackendController;

class PortfolioItemController extends BackendController
{
    
      protected  $path_image = '/public/portfolio';
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PortfolioItem  $portfolioItem
     * @return \Illuminate\Http\Response
     */
    public function show(PortfolioItem $portfolioItem)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PortfolioItem  $portfolioItem
     * @return \Illuminate\Http\Response
     */
    public function edit(PortfolioItem $portfolioItem)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PortfolioItem  $portfolioItem
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PortfolioItem $portfolioItem)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PortfolioItem  $portfolioItem
     * @return \Illuminate\Http\Response
     */
    public function destroy(PortfolioItem $portfolioItem)
    {
        //
    }
}

app/Http/Controllers/Backend/ServicesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Service;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Http\Controllers\Backend\BackendController;

class ServicesController extends BackendController
{
    

    protected  $path_image = '/public/services';

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
         $services = Service::all(); 

        // dd( $services->count() );

         return view('backend.services.index')->with([
                         'services' => $services
                     ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
         return view('backend.services.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
             $service = new Service;
      
            $this->validate($request, [
                'heading' => 'required|max:255',
                'upload_img' => 'required|image',
                'description' => 'required',
              ]);

            //-------
            $upload_img = $request->file('upload_img'); 
            $ext_img = $upload_img->getClientOriginalExtension();

            $new_name_img = str_random(20).'.'.$ext_img;

            $storage_img = $upload_img->storeAs($this->path_image,$new_name_img);
             
            $url_storage_img = Storage::url($storage_img);

            //-------------

            $service->heading = e($request->heading);
            $service->description = e($request->description);
            $service->thumbnail = $url_storage_img;

          $service->save(); 
           
         return redirect('admin/services')->with('status', 'Slide Created!');



    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function show(Service $service)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function edit(Service $service)
    {
        //
        return view('backend.services.edit')->with([
                         'service' => $service
                     ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Service $service)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Service  $service
     * @return \Illuminate\Http\Response
     */
    public function destroy(Service $service)
    {
        //
               $old_url_img = $service->thumbnail;

               $pos =  strpos($old_url_img, '/',1); 
               // "/storage/slides/slide_17.jpg"

               $puth = substr($old_url_img,  ($pos + 1));
               // "slides/slide_17.jpg"

                $exists = Storage::disk('public')->exists( $puth );

                 if( $exists ){
                    $delfiles = Storage::disk('public')->delete( $puth );
                  }
   

      $result  = $service->delete();  

      return response()->json($result);





    }
}

app/Http/Controllers/Backend/SlidesController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Slide;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Http\File;
use App\Http\Controllers\Backend\BackendController;

class SlidesController extends BackendController
{
  
    protected  $path_image = '/public/slides';
    protected  $status_edit = true;



    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $slides = Slide::all(); 

         return view('backend.slides.index')->with([
                         'slides' => $slides
                     ]);

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // 
        $this->status_edit = false;
        return view('backend.slides.create')->with([
                         'status_edit' => $this->status_edit
                     ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
    
            $slide = new Slide;
      
            $this->validate($request, [
                'heading' => 'required|max:255',
                'upload_img' => 'required|image',
                'description' => 'required',
              ]);

            //-------
            $upload_img = $request->file('upload_img'); 
            $ext_img = $upload_img->getClientOriginalExtension();

            $slide_img = str_random(20).'.'.$ext_img;

            $url_img = $upload_img->storeAs($this->path_image,$slide_img);
             
            $url_slide_img = Storage::url($url_img);

            //-------------

            $slide->heading = e($request->heading);
            $slide->description = e($request->description);
            $slide->slide_img = $url_slide_img;

          $slide->save(); 
           
         return redirect('admin/slides')->with('status', 'Slide Created!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function show(Slide $slide)
    {
        //
        echo "string";
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function edit(Slide $slide)
    {

         $this->status_edit = true;
         return view('backend.slides.edit')->with([
                         'slide' => $slide,
                         'status_edit' => $this->status_edit
                     ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Slide $slide)
    {
        //
        
            $this->validate($request, [
                'heading' => 'required|max:255',
                'upload_img' => 'image',
                'description' => 'required',
              ]);

            //-------
            //   dd($old_url_img);

           if ($request->hasFile('upload_img')) {

               $old_url_img = $slide->slide_img;

               $pos =  strpos($old_url_img, '/',1); 
               // "/storage/slides/slide_17.jpg"

               $puth = substr($old_url_img,  ($pos + 1));
               // "slides/slide_17.jpg"

                $exists = Storage::disk('public')->exists( $puth );

                 if( $exists ){
                    $delfiles = Storage::disk('public')->delete( $puth );
                  }
   

                $upload_img = $request->file('upload_img'); 
                $ext_img = $upload_img->getClientOriginalExtension();

                $slide_img = str_random(20).'.'.$ext_img;

                $url_img = $upload_img->storeAs($this->path_image,$slide_img);
                 
                $url_slide_img = Storage::url($url_img);

                $slide->slide_img = $url_slide_img;
            } 
            //---END if()  ---------

            $slide->heading = e($request->heading);
            $slide->description = e($request->description);
            
         $slide->save();     

         return redirect('admin/slides')->with('status', 'Slide Update!'); 

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Slide  $slide
     * @return \Illuminate\Http\Response
     */
    public function destroy(Slide $slide)
    {
        //
           //

               $old_url_img = $slide->slide_img;

               $pos =  strpos($old_url_img, '/',1); 
               // "/storage/slides/slide_17.jpg"

               $puth = substr($old_url_img,  ($pos + 1));
               // "slides/slide_17.jpg"

                $exists = Storage::disk('public')->exists( $puth );

                 if( $exists ){
                    $delfiles = Storage::disk('public')->delete( $puth );
                  }
   
       
     // dd($slide)

      $result  = $slide->delete();  

      return response()->json($result);



    }
}

resources/views/backend/slides/create.blade.php
@extends('backend.layouts.backend')

@section('content')


  <div class="content-wrapper">
    <div class="container-fluid">

      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ url('/admin') }}">Analytics</a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{ url('/admin/slides') }}">Slides</a>
        </li>
        <li class="breadcrumb-item active">Create Slide</li>
      </ol>

     

      <!-- Services Create Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> {{ __('Create Slide') }}
        </div>

        <div class="card-body">  

<!-- Form   -->

    <form method="POST" action="{{ route('slides.store') }}" enctype="multipart/form-data" >
        @csrf

      <div class="form-group row">
          <label for="heading" class="col-md-4 col-form-label text-md-right">{{ __('Heading') }}</label>

          <div class="col-md-6">
              <input id="heading" type="text" class="form-control @error('heading') is-invalid @enderror" name="heading" value="{{ old('heading') }}" required autocomplete="heading" autofocus>

              @error('heading')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

      <div class="form-group row">
       
        <div class="col-md-6 offset-md-4">
            <img id="image_file" src=" {{ asset('storage/slides/1900x1080.png') }} " width="100%" height="200" > 
        </div>  
      </div>  


      <div class="form-group row">
          <label for="upload_img" class="col-md-4 col-form-label text-md-right">{{ __('Image for slide') }}  
          </label>

          <div class="col-md-6">

              <input id="upload_img" type="file" class="form-control-file"  name="upload_img" required autocomplete="upload_img">

                  @error('upload_img')
                    <p><span style="margin-top: .25rem; font-size: .875rem; color: #dc3545;">
                      <strong>{{ $message }}</strong>
                    </span></p>
                  @enderror
              
          </div> 
      </div>
 

      <div class="form-group row">
          <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

          <div class="col-md-6">
              <textarea  id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="3" required >{{ old('description') }}</textarea>

              @error('description')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

       <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
            </div>
        </div>

    </form>

       
        </div> <!-- /.card-body -->

        <div class="card-footer small text-muted">
              Updated yesterday at 11:59 PM 
        </div> <!-- /.card-footer -->
      </div><!-- /.card -->


    </div>
  </div>
  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
  
@endsection

    
@push('script_Change_Image')

  <script src="{{asset('backend')}}/js/change-image.js"></script>
  
@endpush

		

resources/views/backend/slides/edit.blade.php
@extends('backend.layouts.backend')

@section('content')


  <div class="content-wrapper">
    <div class="container-fluid">

      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ url('/admin') }}"> {{ __('Analytics') }} </a>
        </li>
        <li class="breadcrumb-item">
          <a href="{{ url('/admin/slides') }}"> {{ __('Slides')  }}  </a>
        </li>
        <li class="breadcrumb-item active"> {{ __('Edit Slide') }}  </li>
      </ol>

     

      <!-- Slide Edit Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> {{ __('Edit Slide') }}
        </div>

        <div class="card-body">  

<!-- Form   -->

    <form method="POST" action="{{ route('slides.update',$slide) }}" enctype="multipart/form-data" >
        @csrf
        {{ method_field('PUT') }}

      <div class="form-group row">
          <label for="heading" class="col-md-4 col-form-label text-md-right">{{ __('Heading') }}</label>

          <div class="col-md-6">
              <input id="heading" type="text" class="form-control @error('heading') is-invalid @enderror" name="heading" value="{{ $slide->heading }}" required autocomplete="heading" autofocus>

              @error('heading')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

      <div class="form-group row">
       
        <div class="col-md-6 offset-md-4">
            <img id="image_file" src=" {{ asset( $slide->slide_img ) }} " width="100%" height="200" > 
        </div>  
      </div>  


      <div class="form-group row">
          <label for="upload_img" class="col-md-4 col-form-label text-md-right">{{ __('Change Slide Image') }}  
          </label>

          <div class="col-md-6">

              <input id="upload_img" type="file" class="form-control-file"  name="upload_img" autocomplete="upload_img">

                  @error('upload_img')
                    <p><span style="margin-top: .25rem; font-size: .875rem; color: #dc3545;">
                      <strong>{{ $message }}</strong>
                    </span></p>
                  @enderror
              
          </div> 
      </div>
 

      <div class="form-group row">
          <label for="description" class="col-md-4 col-form-label text-md-right">{{ __('Description') }}</label>

          <div class="col-md-6">
              <textarea  id="description" class="form-control @error('description') is-invalid @enderror" name="description" rows="3" required >{{ $slide->description }}</textarea>

              @error('description')
                  <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                  </span>
              @enderror
          </div>
      </div>

       <div class="form-group row mb-0">
            <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                    {{ __('Save') }}
                </button>
            </div>
        </div>

    </form>

       
        </div> <!-- /.card-body -->

        <div class="card-footer small text-muted">
              
        </div> <!-- /.card-footer -->
      </div><!-- /.card -->


    </div>
  </div>
  <!-- /.container-fluid-->
  <!-- /.content-wrapper-->
  
@endsection

    
@push('script_Change_Image')

  <script src="{{asset('backend')}}/js/change-image.js"></script>
  
@endpush

		

resources/views/backend/slides/index.blade.php
@extends('backend.layouts.backend')

@section('content')


  <div class="content-wrapper">
    <div class="container-fluid">

      <!-- Breadcrumbs-->
       <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{{ route('analytics')  }}">Analytics</a>
        </li>
        <li class="breadcrumb-item active">Slides</li>
      </ol>

     

      <!-- Services DataTables Card-->
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-table"></i> Data Table Slides
        </div>
        <div class="card-body">      

          <div class="table-responsive">
            <table id="TableAddDelButton" class="table table-bordered"  width="100%" cellspacing="0"> 
              <tbody>
                <tr>
                  <td>
                    <a id="btnNew" class="btn btn-primary" href=" {{ route('slides.create') }} "  title="New" role="button"><i class="fa fa-plus-circle fa-lg " aria-hidden="true"></i> New</a>
                  </td>    
                </tr>  
              </tbody>
            </table>          
          </div> 


          <div class="table-responsive">

             <table id="exampleSlide" class="table table-hover table-bordered"  width="100%" cellspacing="0"> 
             
            <thead>
              <tr>
                <th><input  type="checkbox" value="" id="head_check"></th> 
                <th class="d-none">ID</th>
                <th>Image</th>
                <th>Heading</th>
                <th>Description</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th><input  type="checkbox" value="" id="foot_check"></th>
                <th class="d-none">ID</th>
                <th>Image</th>
                <th>Heading</th>
                <th>Description</th>
                <th>Actions</th>
              </tr>
            </tfoot>
            <tbody>

            @if(isset($slides) && ($slides->count()) > 0 )
              @foreach ($slides as $slide)

              <tr id="slide_{{$slide->id}}">
                <td><input  type="checkbox" value="" id="row_check_1"></td>
                <td class="d-none"> {{ $slide->id }} </td>
                <td>  <img src=" {{ asset( $slide->slide_img ) }} "  width="150" height="75">   </td>
                <td> {{ $slide->heading }} </td>
                <td> {{ $slide->description }} </td>
                
                <td> 
                  <a id="btnEdit" class="btn btn-success mr-1" href="{{ route('slides.edit',['slide ' => $slide]) }}" title="Edit" role="button"><i class="fa fa-edit fa-lg" aria-hidden="true"></i> Edit</a>

                  <button  id="btnDelete" type="button" class="btn btn-danger  ml-1"  title="Delete" value="{{ $slide->id  }}"  data-url=" {{ route('slides.destroy',['slide ' => $slide]) }}" > <i class="fa fa-trash fa-lg" aria-hidden="true"></i> Delete
                  </button>

                </td>
              </tr>

              @endforeach

             @else 

              <tr>
                <td><input  type="checkbox" value="" id="row_check_2"></td>
                <td class="d-none">No Data</td>
                <td>No Data</td>
                <td>No Data</td>
                <td>No Data</td>
               <td> 
                  <a id="btnEdit" class="btn btn-success mr-1 disabled" href="" title="Edit" role="button"><i class="fa fa-edit fa-lg" aria-hidden="true"></i> Edit</a>

                  <button  id="btnDelete" type="button" disabled class="btn btn-danger  ml-1"  title="Delete" value=""  data-url="" > <i class="fa fa-trash fa-lg" aria-hidden="true"></i> Delete
                  </button>
                </td>

             @endif 


              
             </tbody> 
           </table>


          </div>
        </div>
        <div class="card-footer small text-muted">Updated yesterday at 11:59 PM</div>   



      <meta name="_token" content="{!! csrf_token() !!}" />

      </div>
    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
  
@endsection

    
@push('script_Slides')



  <script type="text/javascript">

// DESC  //  ASC
  $(document).ready(function(){
      
      var selected = [];

     var table = $("#exampleSlide1").DataTable({

      "order": [
          [ 1, "desc" ]
        ],
       "columnDefs": [
          { "searchable": false, "targets": 0 },
          { "orderable": false, "targets": 0 },
          { "searchable": false, "targets": 2 },
          { "orderable": false, "targets": 2 },
          { "searchable": false, "targets": 5 },
          { "orderable": false, "targets": 5 },
        ],
         "lengthMenu": [[5,10, 25, 50, -1], [5,10, 25, 50, "All"]],
          "language": {
          //  "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Russian.json"
            "url": "//cdn.datatables.net/plug-ins/1.10.19/i18n/Ukrainian.json"
        }         
      });

   //  console.log('table = ',table);

//=====================

     $('#exampleSlide tbody').on('click', 'tr', function () {
        var data = table.row( this ).data();
        //var data = table.row( this );

      console.log('table_data = ',data);


        //alert( 'You clicked on '+data[1]+'\'s row' );
    } );

//==============
   

    //delete Slide and remove it from list
    $(document).on('click','#btnDelete',function(){
        
        var slide_id = $(this).val();
        var url = $(this).data("url");

        console.log(url, slide_id);
        
    //     debugger;
       
        if(confirm("ВЫ ХОТИТЕ УДАЛИТЬ ЗАПИСЬ "+ slide_id + " ?"))
        {
             $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                }
            })
            $.ajax({
                type: "DELETE",
                url: url,
                processData : false,
                contentType : false,
                success: function (data) {
                    console.log(data);
                    $("#slide_" + slide_id).remove();
                },
                error: function (data) {
                    console.log('Error:', data);
                }
            });
         }; // end if
       });


    

  });
    
  </script>

  
@endpush

		